import{a as L,S as w,i as p}from"./assets/vendor-D73Uttp0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();function f(t=[]){const r={webformatURL:"https://salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png",tags:"",largeImageURL:"https://salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png",likes:0,views:0,comments:0,downloads:0};return t.map(({webformatURL:n,tags:a,largeImageURL:e,likes:s,views:i,comments:y,downloads:g}=r)=>`<li class="js-item item"><a  href='${e}'>
  <img src="${n}" alt="${a}" data-largeImageURL="${e}" ></a>
  <ul class="descriptions">
    <li class="description" >Likes <span class="span">${s}</span></li>
    <li class="description">Views <span class="span">${i}</span></li>
    <li class="description">Comments <span class="span">${y}</span></li>
    <li class="description">Downloads <span class="span">${g}</span></li>
  </ul>
</li>`).join("")}const b="https://pixabay.com/api/",S={key:"47002801-76ba89481123b51ee1293cd3a",image_type:"photo",orientation:"horizontal",safesearch:!0};async function h(t,r,n){try{const a=new URLSearchParams({...S,q:t,page:r,per_page:n});return(await L(`${b}?${a}`)).data}catch(a){return a}}const o={form:document.querySelector(".js-form"),input:document.querySelector(".js-input"),container:document.querySelector(".js-list"),loader:document.querySelector(".loader"),btnSearch:document.querySelector(".js-btnSearch"),btnLoad:document.querySelector(".js-btnLoad")};let c=1,l;const d=15;o.form.addEventListener("submit",v);o.btnLoad.addEventListener("click",O);let m=new w(".gallery a",{captionDelay:250,captionsData:"alt"});async function v(t){if(t.preventDefault(),l=t.target.elements.search.value,!l.trim())return p.error({message:"Please fill in the field!",position:"topRight"});u(),o.container.innerHTML="";try{const r=await h(l,c,d);if(r.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");if(Math.floor(r.totalHits/d)<c)throw u(),new Error("We're sorry, but you've reached the end of search results.");o.container.innerHTML=f(r.hits),m.refresh(),q()}catch(r){p.error({message:r.message,position:"topRight"})}finally{o.loader.classList.remove("displayOn")}t.target.reset()}async function O(){c+=1;try{const t=await h(l,c,d);if(t.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");if(Math.floor(t.totalHits/d)<c)throw u(),new Error("We're sorry, but you've reached the end of search results.");o.container.insertAdjacentHTML("beforeend",f(t.hits)),$(),m.refresh()}catch(t){p.error({message:t.message,position:"topRight"})}finally{o.loader.classList.remove("displayOn")}}function u(){o.btnLoad.classList.add("displayOff")}function q(){o.btnLoad.classList.remove("displayOff")}function $(){const t=o.container.getBoundingClientRect();window.scrollBy({top:t.height*2,left:t.left,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
