import{S as u,i as l}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function d(a=[]){const r={webformatURL:"https://salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png",tags:"",largeImageURL:"https://salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png",likes:0,views:0,comments:0,downloads:0};return a.map(({webformatURL:s,tags:o,largeImageURL:e,likes:t,views:n,comments:c,downloads:p}=r)=>`<li class="js-item item"><a  href='${e}'>
  <img src="${s}" alt="${o}" data-largeImageURL="${e}" ></a>
  <ul class="descriptions">
    <li class="description" >Likes <span class="span">${t}</span></li>
    <li class="description">Views <span class="span">${n}</span></li>
    <li class="description">Comments <span class="span">${c}</span></li>
    <li class="description">Downloads <span class="span">${p}</span></li>
  </ul>
</li>`).join("")}function f(a,r,s){const o=new URLSearchParams({...s,q:r});return fetch(`${a}?${o}`).then(e=>{if(!e.ok)throw new Error(e.statusText);return e.json()})}const i={form:document.querySelector(".js-form"),input:document.querySelector(".js-input"),container:document.querySelector(".js-list"),loader:document.querySelector(".loader")};i.form.addEventListener("submit",y);const m="https://pixabay.com/api/",h={key:"47002801-76ba89481123b51ee1293cd3a",image_type:"photo",orientation:"horizontal",safesearch:!0};let g=new u(".gallery a",{captionDelay:250,captionsData:"alt"});function y(a){a.preventDefault();const r=a.target.elements.search.value;if(!r.trim())return l.error({message:"Please fill in the field!",position:"topRight"});i.container.innerHTML="",i.loader.classList.add("displayOn"),f(m,r,h).then(s=>{if(s.hits.length===0)throw new Error;i.container.innerHTML=d(s.hits),g.refresh()}).catch(s=>l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})).finally(s=>i.loader.classList.remove("displayOn")),a.target.reset()}
//# sourceMappingURL=index.js.map
